-- MySQL Script generated by MySQL Workbench
-- Sun Jun 12 16:48:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` DEFAULT CHARACTER SET utf8 ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `projeto`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`local` (
  `idlocal` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`pokemon` (
  `idpokemon` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `lvl` INT NULL,
  `shiny` TINYINT NULL,
  `possui` TINYINT NULL,
  `local_idlocal` INT NOT NULL,
  PRIMARY KEY (`idpokemon`, `local_idlocal`),
  UNIQUE INDEX `id_UNIQUE` (`idpokemon` ASC) VISIBLE,
  INDEX `fk_pokemon_local1_idx` (`local_idlocal` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_local1`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `projeto`.`local` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`treinardor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`treinardor` (
  `idtreinardor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtreinardor`),
  UNIQUE INDEX `idtreinardor_UNIQUE` (`idtreinardor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`pokedex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`pokedex` (
  `idpokedex` INT NOT NULL,
  `treinardor_idtreinardor` INT NOT NULL,
  PRIMARY KEY (`idpokedex`, `treinardor_idtreinardor`),
  INDEX `fk_pokedex_treinardor_idx` (`treinardor_idtreinardor` ASC) VISIBLE,
  CONSTRAINT `fk_pokedex_treinardor`
    FOREIGN KEY (`treinardor_idtreinardor`)
    REFERENCES `projeto`.`treinardor` (`idtreinardor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`pokemon_has_pokedex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`pokemon_has_pokedex` (
  `pokemon_idpokemon` INT NOT NULL,
  `pokemon_local_idlocal` INT NOT NULL,
  `pokedex_idpokedex` INT NOT NULL,
  `pokedex_treinardor_idtreinardor` INT NOT NULL,
  PRIMARY KEY (`pokemon_idpokemon`, `pokemon_local_idlocal`, `pokedex_idpokedex`, `pokedex_treinardor_idtreinardor`),
  INDEX `fk_pokemon_has_pokedex_pokedex1_idx` (`pokedex_idpokedex` ASC, `pokedex_treinardor_idtreinardor` ASC) VISIBLE,
  INDEX `fk_pokemon_has_pokedex_pokemon1_idx` (`pokemon_idpokemon` ASC, `pokemon_local_idlocal` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_has_pokedex_pokemon1`
    FOREIGN KEY (`pokemon_idpokemon` , `pokemon_local_idlocal`)
    REFERENCES `projeto`.`pokemon` (`idpokemon` , `local_idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_has_pokedex_pokedex1`
    FOREIGN KEY (`pokedex_idpokedex` , `pokedex_treinardor_idtreinardor`)
    REFERENCES `projeto`.`pokedex` (`idpokedex` , `treinardor_idtreinardor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
